=== Plutinsky/Study-Java/library/Data/matters.xsd
<?xml version="1.0" encoding="windows-1251"?>
<tns:schema xmlns:tns="http://www.w3.org/2001/XMLSchema">
    
    <tns:element name="matters">
        <tns:complexType>
            <tns:sequence>
                <tns:element name="book" type="Book" minOccurs="0" maxOccurs="unbounded" />
                <tns:element name="magazine" type="Magazine" minOccurs="0" maxOccurs="unbounded" />
                <tns:element name="newspaper" type="Newspaper" minOccurs="0" maxOccurs="unbounded" /> 
            </tns:sequence>  
        </tns:complexType>
    </tns:element>
    
    <tns:complexType name="PrintedMatter">
        <tns:sequence>
            <tns:element name="imprint_date" type="tns:date"/>
            <tns:element name="publishing_house" type="PublishingHouse"/>
            <tns:element name="number_pages" type="tns:integer"/>
            <tns:element name="title" type="tns:string"/>
        </tns:sequence>
        <tns:attribute name="id" type="idMatters" use="required"/>
    </tns:complexType>
    
    <tns:simpleType name="PublishingHouse">
        <tns:restriction base="tns:string">
            <tns:enumeration value="Williams"></tns:enumeration>
            <tns:enumeration value="NewYorkTimes"></tns:enumeration>
            <tns:enumeration value="Piter"></tns:enumeration>
            <tns:enumeration value="DailyMail"></tns:enumeration>
            <tns:enumeration value="Science"></tns:enumeration>
            <tns:enumeration value="Esquire"></tns:enumeration>
            <tns:enumeration value="Vogue"></tns:enumeration>
        </tns:restriction>
    </tns:simpleType>
    
    <tns:simpleType name="idMatters">
        <tns:restriction base="tns:ID">
            <tns:pattern value="[a-zA-z]{1}[0-9]{1,7}"/>
        </tns:restriction>
    </tns:simpleType>
    
    <tns:complexType name="Periodical">
        <tns:complexContent>
            <tns:extension base="PrintedMatter">
                <tns:sequence>
                    <tns:element name="number" type="Number" />
                    <tns:element name="periodicity" type="tns:integer" />
                    <tns:element name="redactor" type="tns:string" />
                </tns:sequence>
            </tns:extension>
        </tns:complexContent>	
    </tns:complexType>
    
    <tns:simpleType name="Number">
        <tns:restriction base="tns:string">
            <tns:pattern value="¹[0-9]{1,5}"/>
        </tns:restriction>
    </tns:simpleType>
    
    <tns:complexType name="Magazine">
        <tns:complexContent>
            <tns:extension base="Periodical">
            </tns:extension>
        </tns:complexContent>	
    </tns:complexType>
    
    <tns:complexType name="Newspaper">
        <tns:complexContent>
            <tns:extension base="Periodical">
                <tns:sequence>
                    <tns:element name="topicality" type="tns:integer" />
                </tns:sequence>
            </tns:extension>
        </tns:complexContent>	
    </tns:complexType>
    
    <tns:complexType name="Book">
        <tns:complexContent>
            <tns:extension base="PrintedMatter">
                <tns:sequence>
                    <tns:element name="author" type="tns:string" />
                </tns:sequence>
            </tns:extension>
        </tns:complexContent>	
    </tns:complexType>
        
</tns:schema>

=== Plutinsky/Study-Java/library/Data/matters.xml
<?xml version="1.0" encoding="windows-1251"?>

<matters xmlns:xtns="http://www.w3.org/2001/XMLSchema-instance" xtns:noNamespaceSchemaLocation="matters.xsd">
    <book id = "k503">
        <imprint_date>1999-11-23</imprint_date>
        <publishing_house>Piter</publishing_house>
        <number_pages>452</number_pages>
        <title>Java</title>
        <author>Eckel</author>
    </book>
    
    <magazine id="h324">	
        <imprint_date>2012-01-13</imprint_date>
        <publishing_house>Science</publishing_house>
        <number_pages>122</number_pages>
        <title>Math</title>
        <number>¹3</number>
        <periodicity>4</periodicity>
        <redactor>Petrov</redactor>
    </magazine>	
    
     <newspaper id="q111">
         <imprint_date>2012-10-23</imprint_date>
         <publishing_house>DailyMail</publishing_house>
         <number_pages>23</number_pages>
         <title>News today</title>
         <number>¹4</number>
         <periodicity>3</periodicity>
         <redactor>Sidorov</redactor>
         <topicality>3</topicality>
     </newspaper>                                                                  									
</matters>
